### ISSUE TITLE
Cannot install or update london:body-class

### ISSUE THREAD

**Issue by donwojtallo** [meteor-london/body-class#10]
When trying to install by:
`meteor add london:body-class`
I get this:

```
C:\Users\Wojciech\AppData\Local\.meteor\packages\meteor-tool\1.1.10\mt-os.windows.x86_32\dev_bundle\lib\node_modules\fibers\future.js:278
                                                throw(ex);
                                                      ^
Error: ENOENT, open 'C:\Users\Wojciech\AppData\Local\Temp\mt-1cr2fvj\web.browser\london:body-class.js'
    at Object.Future.wait (C:\Users\Wojciech\AppData\Local\.meteor\packages\meteor-tool\1.1.10\mt-os.windows.x86_32\dev_bundle\lib\node_modules\fibers\future.js:398:15)
    at C:\tools\fs\files.js:1331:28
    at Object.wrapper [as open] (C:\tools\fs\files.js:1334:20)
    at Object.files.readBufferWithLengthAndOffset (C:\tools\fs\files.js:1474:20)
    at C:\tools\isobuild\isopack.js:984:26
    at Array.forEach (native)
    at Function._.each._.forEach (C:\Users\Wojciech\AppData\Local\.meteor\packages\meteor-tool\1.1.10\mt-os.windows.x86_32\dev_bundle\lib\node_modules\underscore\underscore.js:79:11)
    at C:\tools\isobuild\isopack.js:982:9
    at Array.forEach (native)
    at Function._.each._.forEach (C:\Users\Wojciech\AppData\Local\.meteor\packages\meteor-tool\1.1.10\mt-os.windows.x86_32\dev_bundle\lib\node_modules\underscore\underscore.js:79:11)
    at [object Object]._.extend._loadUnibuildsFromPath (C:\tools\isobuild\isopack.js:942:7)
    at C:\tools\packaging\tropohouse.js:500:19
```

I tried this on old project, new and also tried `meteor reset`. Nothing work.
I think this is because the colon in filename. Colons are generally forbidden in filenames on Windows. When I try to clone this repo I see this:

```
error: Invalid path 'london:body-class.js'
```

But this package was working sometime ago...

**Comment by JMonvoisin** [comment]
Sorry, this is an old (open) report, but I have the same issue here on Windows.
Does anyone has any idea how to fix this?
Thx
